services:
  - type: web
    name: hotel-management-system
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: PAYHERE_MERCHANT_ID
        sync: false
      - key: PAYHERE_MERCHANT_KEY
        sync: false
      - key: PAYHERE_SANDBOX
        value: "true"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
